### ISSUE TITLE
URLs have // and result in 404

### ISSUE THREAD

**Issue by yurrriq** [NixOS/mvn2nix-maven-plugin#10]
When using this on a Clojure project I had to do the following after generating `project-info.json`:

```fish
sed -i 's|\(maven2/\)/|\1/|g'          project-info.json
sed -i 's|\(clojars\.org/repo\)/|\1|g' project-info.json
```

**Comment by yurrriq** [comment]
N.B. This may be an issue with `build-maven` instead. I'm using [this version](https://github.com/NixOS/nixpkgs/blob/89747d357badd51485a2c893ee3803d49def058b/pkgs/build-support/build-maven.nix).

**Comment by shlevy** [comment]
Can you share an example of a project spec with a bad URL?

**Comment by yurrriq** [comment]
Sure, I'll make a minimal failing example. It could also be a problem with `lein pom`.

**Comment by yurrriq** [comment]
Ok, so the problem arose when I patched my `project.clj` to add `:local-repo "home/.m2/repo"` and didn't use the hacked `java` from [lein-nix-build](https://github.com/madriska/lein-nix-build). That works for leiningen, but not for maven. I'll submit a patch to lein-nix-build instead. Thanks for inspiring me to look into it further. :smile:

**Comment by charles-dyfis-net** [comment]
I encountered this *without* `:local-repo` in use, but with a `<repository><url>` with a trailing `/` in the path.
